import 'package:rs_libras/model/categories.dart';
import 'package:rs_libras/model/elements_categories.dart';

final cores = Categories(
  id: 0,
  name: "Cores",
  elements: [
    ElementsCategories(id: 0, name: "Branco", url: "b9eHsRjx4ec"),
    ElementsCategories(id: 1, name: "Preto", url: "0DHWd0pjLvY"),
    ElementsCategories(id: 2, name: "Cinza", url: "Y0blVoWwZ1U"),
    ElementsCategories(id: 3, name: "Azul", url: "B0m89hLesEo"),
    ElementsCategories(id: 4, name: "Verde", url: "fnPCwwtI58U"),
    ElementsCategories(id: 5, name: "Vermelho", url: "QGqVEisRsH8"),
    ElementsCategories(id: 6, name: "Amarelo", url: "Q9A7QYMywfY"),
    ElementsCategories(id: 7, name: "Roxo", url: "vamR6MOGqio"),
    ElementsCategories(id: 8, name: "Laranja", url: "_MfqLT7JJxk"),
    ElementsCategories(id: 9, name: "Marrom", url: "5asFM8p9uG0"),
    ElementsCategories(id: 10, name: "Rosa", url: "rlbor7_Xojg"),
    ElementsCategories(id: 11, name: "Bege", url: "o40vxEQ3zI8"),
    ElementsCategories(id: 12, name: "Ouro", url: "SwasoQjl38I"),
    ElementsCategories(id: 13, name: "Vinho", url: "pfGDzv0vZ_A"),
    ElementsCategories(id: 14, name: "Lilás", url: "ixRvF9kd4P0"),
    ElementsCategories(id: 15, name: "Claro", url: "clPkSUDPyOQ"),
    ElementsCategories(id: 16, name: "Escuro", url: "jN-aA_6iz80"),
    ElementsCategories(id: 17, name: "Colorido", url: "OAplMN_kIC0"),
  ],
);

final frutas = Categories(
  id: 1,
  name: "Frutas",
  elements: [
    ElementsCategories(id: 0, name: "Maçã", url: "url"),
    ElementsCategories(id: 1, name: "Uva", url: "url"),
    ElementsCategories(id: 2, name: "Bergamota", url: "url"),
    ElementsCategories(id: 3, name: "Pêssego", url: "url"),
    ElementsCategories(id: 4, name: "Caqui", url: "url"),
    ElementsCategories(id: 5, name: "Ameixa", url: "url"),
    ElementsCategories(id: 6, name: "Morango", url: "url"),
    ElementsCategories(id: 7, name: "Kiwi", url: "url"),
    ElementsCategories(id: 8, name: "Melancia", url: "url"),
    ElementsCategories(id: 9, name: "Abacaxi", url: "url"),
    ElementsCategories(id: 10, name: "Banana", url: "url"),
    ElementsCategories(id: 11, name: "Laranja", url: "url"),
    ElementsCategories(id: 12, name: "Limão", url: "url"),
    ElementsCategories(id: 13, name: "Mamão", url: "url"),
    ElementsCategories(id: 14, name: "Manga", url: "url"),
    ElementsCategories(id: 15, name: "Maracujá", url: "url"),
    ElementsCategories(id: 16, name: "Melão", url: "url"),
    ElementsCategories(id: 17, name: "Goiaba", url: "url"),
    ElementsCategories(id: 18, name: "Cereja", url: "url"),
    ElementsCategories(id: 19, name: "Figo", url: "url"),
  ],
);

final roupas = Categories(
  id: 2,
  name: "Roupas",
  elements: [
    ElementsCategories(id: 0, name: "Camiseta", url: "url"),
    ElementsCategories(id: 1, name: "Camisa", url: "url"),
    ElementsCategories(id: 2, name: "Blusa", url: "url"),
    ElementsCategories(id: 3, name: "Calça", url: "url"),
    ElementsCategories(id: 4, name: "Bermuda", url: "url"),
    ElementsCategories(id: 5, name: "Touca", url: "url"),
    ElementsCategories(id: 6, name: "Saia", url: "url"),
    ElementsCategories(id: 7, name: "Vestido", url: "url"),
    ElementsCategories(id: 8, name: "Casaco", url: "url"),
    ElementsCategories(id: 9, name: "Sutiã", url: "url"),
    ElementsCategories(id: 10, name: "Sapato de Salto", url: "url"),
    ElementsCategories(id: 11, name: "Meia", url: "url"),
    ElementsCategories(id: 12, name: "Cueca", url: "url"),
    ElementsCategories(id: 13, name: "Calcinha", url: "url"),
    ElementsCategories(id: 14, name: "Cachecol", url: "url"),
    ElementsCategories(id: 15, name: "Luva", url: "url"),
    ElementsCategories(id: 16, name: "Chapéu", url: "url"),
    ElementsCategories(id: 17, name: "Sapato", url: "url"),
    ElementsCategories(id: 18, name: "Tênis", url: "url"),
    ElementsCategories(id: 19, name: "Boné", url: "url"),
    ElementsCategories(id: 20, name: "Biquíni", url: "url"),
  ],
);

final profissoes = Categories(
  id: 3,
  name: "Profissões",
  elements: [
    ElementsCategories(id: 0, name: "Médico", url: "url"),
    ElementsCategories(id: 1, name: "Engenheiro", url: "url"),
    ElementsCategories(id: 2, name: "Advogado", url: "url"),
    ElementsCategories(id: 3, name: "Professor", url: "url"),
    ElementsCategories(id: 4, name: "Enfermeiro", url: "url"),
    ElementsCategories(id: 5, name: "Psicólogo", url: "url"),
    ElementsCategories(id: 6, name: "Administrador", url: "url"),
    ElementsCategories(id: 7, name: "Contador", url: "url"),
    ElementsCategories(id: 8, name: "Técnico em Enfermagem", url: "url"),
    ElementsCategories(id: 9, name: "Farmacêutico", url: "url"),
    ElementsCategories(id: 10, name: "Dentista", url: "url"),
    ElementsCategories(id: 11, name: "Fisioterapeuta", url: "url"),
    ElementsCategories(id: 12, name: "Veterinário", url: "url"),
    ElementsCategories(id: 13, name: "Arquiteto", url: "url"),
    ElementsCategories(id: 14, name: "Motorista", url: "url"),
    ElementsCategories(id: 15, name: "Mecânico", url: "url"),
    ElementsCategories(id: 16, name: "Eletricista", url: "url"),
    ElementsCategories(id: 17, name: "Vendedor", url: "url"),
    ElementsCategories(id: 18, name: "Jornalista", url: "url"),
    ElementsCategories(id: 19, name: "Policial", url: "url"),
  ],
);

final adjetivos = Categories(
  id: 4,
  name: "Adjetivos",
  elements: [
    ElementsCategories(id: 0, name: "Lindo", url: "url"),
    ElementsCategories(id: 1, name: "Feio", url: "url"),
    ElementsCategories(id: 2, name: "Alto", url: "url"),
    ElementsCategories(id: 3, name: "Baixo", url: "url"),
    ElementsCategories(id: 4, name: "Gordo", url: "url"),
    ElementsCategories(id: 5, name: "Magro", url: "url"),
    ElementsCategories(id: 6, name: "Bom", url: "url"),
    ElementsCategories(id: 7, name: "Mau", url: "url"),
    ElementsCategories(id: 8, name: "Forte", url: "url"),
    ElementsCategories(id: 9, name: "Fraco", url: "url"),
    ElementsCategories(id: 10, name: "Rápido", url: "url"),
    ElementsCategories(id: 11, name: "Devagar", url: "url"),
    ElementsCategories(id: 12, name: "Caloroso", url: "url"),
    ElementsCategories(id: 13, name: "Frio", url: "url"),
    ElementsCategories(id: 14, name: "Brilhante", url: "url"),
    ElementsCategories(id: 15, name: "Escuro", url: "url"),
    ElementsCategories(id: 16, name: "Limpo", url: "url"),
    ElementsCategories(id: 17, name: "Sujo", url: "url"),
    ElementsCategories(id: 18, name: "Fácil", url: "url"),
    ElementsCategories(id: 19, name: "Difícil", url: "url"),
    ElementsCategories(id: 20, name: "Grande", url: "url"),
    ElementsCategories(id: 21, name: "Pequeno", url: "url"),
    ElementsCategories(id: 22, name: "Feliz", url: "url"),
    ElementsCategories(id: 23, name: "Triste", url: "url"),
    ElementsCategories(id: 24, name: "Simples", url: "url"),
    ElementsCategories(id: 25, name: "Complicado", url: "url"),
    ElementsCategories(id: 26, name: "Jovem", url: "url"),
    ElementsCategories(id: 27, name: "Velho", url: "url"),
    ElementsCategories(id: 28, name: "Burro", url: "url"),
    ElementsCategories(id: 29, name: "Esperto", url: "url")
  ],
);

final verbos = Categories(
  id: 5,
  name: "Verbos",
  elements: [
    ElementsCategories(id: 0, name: "Amar", url: "url"),
    ElementsCategories(id: 1, name: "Andar", url: "url"),
    ElementsCategories(id: 2, name: "Cantar", url: "url"),
    ElementsCategories(id: 3, name: "Chorar", url: "url"),
    ElementsCategories(id: 4, name: "Comer", url: "url"),
    ElementsCategories(id: 5, name: "Conversar", url: "url"),
    ElementsCategories(id: 6, name: "Correr", url: "url"),
    ElementsCategories(id: 7, name: "Dançar", url: "url"),
    ElementsCategories(id: 8, name: "Descansar", url: "url"),
    ElementsCategories(id: 9, name: "Dormir", url: "url"),
    ElementsCategories(id: 10, name: "Estudar", url: "url"),
    ElementsCategories(id: 11, name: "Falar", url: "url"),
    ElementsCategories(id: 12, name: "Fazer", url: "url"),
    ElementsCategories(id: 13, name: "Gostar", url: "url"),
    ElementsCategories(id: 14, name: "Ler", url: "url"),
    ElementsCategories(id: 15, name: "Nadar", url: "url"),
    ElementsCategories(id: 16, name: "Ouvir", url: "url"),
    ElementsCategories(id: 17, name: "Pensar", url: "url"),
    ElementsCategories(id: 18, name: "Pular", url: "url"),
    ElementsCategories(id: 19, name: "Sair", url: "url"),
    ElementsCategories(id: 20, name: "Sentir", url: "url"),
    ElementsCategories(id: 21, name: "Sorrir", url: "url"),
    ElementsCategories(id: 22, name: "Tomar", url: "url"),
    ElementsCategories(id: 23, name: "Trabalhar", url: "url"),
    ElementsCategories(id: 24, name: "Viajar", url: "url"),
    ElementsCategories(id: 25, name: "Ver", url: "url"),
    ElementsCategories(id: 26, name: "Vestir", url: "url"),
    ElementsCategories(id: 27, name: "Visitar", url: "url"),
    ElementsCategories(id: 28, name: "Viver", url: "url"),
    ElementsCategories(id: 29, name: "Voltar", url: "url"),
    ElementsCategories(id: 30, name: "Aprender", url: "url"),
    ElementsCategories(id: 31, name: "Ensinar", url: "url"),
    ElementsCategories(id: 32, name: "Lutar", url: "url"),
    ElementsCategories(id: 33, name: "Desenhar", url: "url"),
    ElementsCategories(id: 34, name: "Escrever", url: "url"),
    ElementsCategories(id: 35, name: "Fotografar", url: "url"),
    ElementsCategories(id: 36, name: "Desistir", url: "url"),
    ElementsCategories(id: 37, name: "Quebrar", url: "url"),
    ElementsCategories(id: 38, name: "Consertar", url: "url"),
    ElementsCategories(id: 39, name: "Cozinhar", url: "url"),
  ],
);

final alfabeto = Categories(
  id: 6,
  name: "Alfabeto",
  elements: [
    ElementsCategories(id: 0, name: "A", url: "url"),
    ElementsCategories(id: 1, name: "B", url: "url"),
    ElementsCategories(id: 2, name: "C", url: "url"),
    ElementsCategories(id: 3, name: "D", url: "url"),
    ElementsCategories(id: 4, name: "E", url: "url"),
    ElementsCategories(id: 5, name: "F", url: "url"),
    ElementsCategories(id: 6, name: "G", url: "url"),
    ElementsCategories(id: 7, name: "H", url: "url"),
    ElementsCategories(id: 8, name: "I", url: "url"),
    ElementsCategories(id: 9, name: "J", url: "url"),
    ElementsCategories(id: 10, name: "K", url: "url"),
    ElementsCategories(id: 11, name: "L", url: "url"),
    ElementsCategories(id: 12, name: "M", url: "url"),
    ElementsCategories(id: 13, name: "N", url: "url"),
    ElementsCategories(id: 14, name: "O", url: "url"),
    ElementsCategories(id: 15, name: "P", url: "url"),
    ElementsCategories(id: 16, name: "Q", url: "url"),
    ElementsCategories(id: 17, name: "R", url: "url"),
    ElementsCategories(id: 18, name: "S", url: "url"),
    ElementsCategories(id: 19, name: "T", url: "url"),
    ElementsCategories(id: 20, name: "U", url: "url"),
    ElementsCategories(id: 21, name: "V", url: "url"),
    ElementsCategories(id: 22, name: "W", url: "url"),
    ElementsCategories(id: 23, name: "X", url: "url"),
    ElementsCategories(id: 24, name: "Y", url: "url"),
    ElementsCategories(id: 25, name: "Z", url: "url")
  ],
);

final meiosDeTransporte = Categories(
  id: 7,
  name: "Meios de Transporte",
  elements: [
    ElementsCategories(id: 0, name: "Carro", url: "url"),
    ElementsCategories(id: 1, name: "Ônibus", url: "url"),
    ElementsCategories(id: 2, name: "Skate", url: "url"),
    ElementsCategories(id: 3, name: "Trem", url: "url"),
    ElementsCategories(id: 4, name: "Bicicleta", url: "url"),
    ElementsCategories(id: 5, name: "Moto", url: "url"),
    ElementsCategories(id: 6, name: "Avião", url: "url"),
    ElementsCategories(id: 7, name: "Barco", url: "url"),
    ElementsCategories(id: 8, name: "Helicóptero", url: "url"),
    ElementsCategories(id: 9, name: "Caminhão", url: "url"),
    ElementsCategories(id: 10, name: "Carroça", url: "url"),
    ElementsCategories(id: 11, name: "Cavalo", url: "url"),
    ElementsCategories(id: 12, name: "Trator", url: "url"),
  ],
);

final tempo = Categories(
  id: 8,
  name: "Tempo",
  elements: [
    ElementsCategories(id: 0, name: "Segundo", url: "url"),
    ElementsCategories(id: 1, name: "Minuto", url: "url"),
    ElementsCategories(id: 2, name: "Hora", url: "url"),
    ElementsCategories(id: 3, name: "Dia", url: "url"),
    ElementsCategories(id: 4, name: "Semana", url: "url"),
    ElementsCategories(id: 5, name: "Mês", url: "url"),
    ElementsCategories(id: 6, name: "Ano", url: "url"),
    ElementsCategories(id: 7, name: "Cedo", url: "url"),
    ElementsCategories(id: 8, name: "Tarde", url: "url"),
    ElementsCategories(id: 9, name: "Noite", url: "url"),
    ElementsCategories(id: 10, name: "Amanhecer", url: "url"),
    ElementsCategories(id: 11, name: "Anoitecer", url: "url"),
    ElementsCategories(id: 12, name: "Madrugada", url: "url"),
    ElementsCategories(id: 13, name: "Atrasado", url: "url"),
    ElementsCategories(id: 14, name: "Adiantado", url: "url"),
    ElementsCategories(id: 15, name: "Futuro", url: "url"),
    ElementsCategories(id: 16, name: "Passado", url: "url"),
    ElementsCategories(id: 17, name: "Presente", url: "url"),
    ElementsCategories(id: 18, name: "Ontem", url: "url"),
    ElementsCategories(id: 19, name: "Hoje", url: "url"),
    ElementsCategories(id: 20, name: "Amanhã", url: "url"),
  ],
);

final List<Categories> categories = [
  cores,
  frutas,
  roupas,
  profissoes,
  adjetivos,
  verbos,
  alfabeto,
  meiosDeTransporte,
  tempo,
];
